// client/src/components/Controls.vue
<template>
  <div class="controls" @click.self="deselectTorrents()">

    <div class="buttons">
      <button v-if="false" @click="toggleVPN()">Toggle VPN</button>
      <button @click="getTVFolder()" :disabled="disabled">
        Move to TV Shows
        <img src="../assets/plextv-icon.svg" width="25" />
      </button>
      <button @click="moveMovie()" :disabled="disabled">
        Move to Movies
        <img src="../assets/plextv-icon.svg" width="25" />
      </button>
      <button
        v-if="selectedTorrent.id"
        @click="handleStartStop()"
        :disabled="disabled"
      >
        {{ playPauseText }}
      </button>

      <button
        v-if="selectedTorrent.id"
        @click="removeFromList(selectedTorrent)"
        :disabled="disabled"
        class="danger"
      >
        Remove
      </button>
    </div>
  </div>
</template>

<script>
import { get, post, _delete } from '../functions';
const AppState = {};
import { txStatus } from '../functions';

export default {
  props: ['selectedTorrent'],

  data() {
    return {
      playPauseText: 'Start',
    };
  },

  computed: {
    disabled() {
      return !this.selectedTorrent.id || this.isLoading;
    }
  },

  methods: {
    toggleVPN() {
      let action;
      if (this.vpnStatus == 'ACTIVE') {
        action = 'stop';
      } else {
        action = 'start';
      }

      post('/vpn', { action }).then(response => {
        if (response.success) {
          // console.log(`vpn start: success`);
          get('/vpn-status').then(result => {
            this.vpnStatus = result.status;
          });
        }
      });
    },

    deselectTorrents() {
      AppState.$emit('torrentSelect', { id: null });
    },

    openModal() {
      AppState.$emit('openModal', { msg: 'Start torrent' });
    },

    getTVFolder() {
      // const self = this;
      post('/guess-tv-show', { torrentName: this.selectedTorrent.name }).then(
        response => {
          // console.log('response from /guess-tv-show', response);
          const { show, season, error } = response;
          const msg = `Move to ${show} - ${season} folder?`;

          // console.log(msg);
          if (error) {
            // handle error ?
          }

          AppState.$emit('openModal', {
            msg,
            show,
            season,
            handleConfirm: () => {
              this.moveTVShow(this.selectedTorrent, show, season);
            }
          });
        }
      );
    },

    moveMovie() {
      this.isLoading = true;
      post('/move-movie', this.selectedTorrent).then(response => {
        // console.log(response);

        if (response.success) {
          this.removeFromList(this.selectedTorrent);
        }
      });
    },

    moveTVShow(torrent, show, season) {
      this.isLoading = true;
      // console.log('Controls will move TV Show');
      // console.log(torrent, show, season);
      post('/move-tv-show', { torrent, show, season }).then(response => {
        if (response.success) {
          this.removeFromList(this.selectedTorrent);
        }
      });
    },

    removeFromList(torrent) {
      this.isLoading = true;
      _delete('/torrents', { id: torrent.id }).then(() => {
        // console.log('removing torrents from list.');
        // console.log(response);

        AppState.$emit('torrentListShouldChange');
        this.isLoading = false;
      });
    },

    handleStartStop() {
      post('/pause', {
        id: this.selectedTorrent.id,
        action: this.playPauseText.toLowerCase()
      }).then(() => {
        // console.log(`start/stop response`, response);
        AppState.$emit('torrentListShouldChange');
      });
    }
  },

  watch: {
    selectedTorrent: {
      deep: true,
      handler(newVal) {
        if (
          newVal.status === txStatus.DOWNLOAD ||
          newVal.status === txStatus.SEED
        ) {
          this.playPauseText = 'Stop';
        } else {
          this.playPauseText = 'Start';
        }
      }
    }
  },

  created() {
    get('/vpn-status').then(result => {
      this.vpnStatus = result.status;
    });

    setInterval(() => {
      get('/vpn-status').then(result => {
        this.vpnStatus = result.status;
      });
    }, 60000);
  }
};
</script>

<style lang="scss">
.controls {
  background: rgb(45, 45, 56);
  color: white;

  button {
    width: 90%;
    font-family: 'Avenir', sans-serif;
    display: block;
    background-color: #3b3b48;
    color: white;
    border-radius: 5px;
    font-size: 1rem;
    padding: 1rem;
    margin: 1rem auto;
    border: none;
    outline: none;
    box-shadow: 0 0 8px rgba(16, 10, 39, 0.5);
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;

    &:active {
      background-color: #408fcf;
    }

    &.danger {
      background-color: #753535;
    }

    &[disabled] {
      opacity: 0.5;
    }
  }

  .status-bar {
    background: rgb(32, 32, 39);
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    .indicator {
      display: flex;
      align-items: center;
      background: rgb(32, 32, 39);
      padding: 5px;
      color: lightgrey;
    }
    .statusLight {
      width: 0.75rem;
      height: 0.75rem;
      border: solid 1px lightgrey;
      border-radius: 50%;
      display: inline-block;
      margin: 0 10px;
      background-color: #c76172;

      &.active {
        background-color: #2bca2b;
      }
    }
  }

  @media screen and (max-width: 415px) {
    width: 100vw;
    height: 100px;
    overflow: hidden;

    .buttons {
      display: flex;
      height: 90px;
      overflow-x: scroll;
      overflow-y: hidden;
    }

    button {
      display: flex;
      flex: 1 0 155px;
      margin: 0.5rem 1rem;
    }
  }
}
</style>

// react-front-end/src/components/Controls.tsx
import React, { useEffect } from 'react';
import { useGlobalState } from '../State';
import classNames from 'classnames';
import spinnerImage from '../assets/spinner.svg';
import plexIcon from '../assets/plextv-icon.svg';
import './styles/controls.scss';
import { get, post, _delete } from '../functions';

export default function Controls() {
  const [state, dispatch] = useGlobalState();
  const disabled = !state.selectedTorrent;
  const playPauseText = 'Stop';

  useEffect(() => {
    get('/vpn-status').then(res => {
      dispatch({ type: 'SET_VPN_STATUS', payload: res.status });
    });

    setInterval(() => {
      get('/vpn-status').then(res => {
        dispatch({ type: 'SET_VPN_STATUS', payload: res.status });
      });
    }, 60000);
  }, [dispatch]);

  const toggleVPN = () => {
    let action;
    if (state.vpnStatus === 'ACTIVE') {
      action = 'stop';
    } else {
      action = 'start';
    }

    post('/vpn', { action }).then(response => {
      if (response.success) {
        console.log(`vpn start: success`);
        get('/vpn-status').then(result => {
          dispatch({ type: 'SET_VPN_STATUS', payload: result.status });
        });
      }
    });
  };

  const openModal = () => {
    dispatch({ type: 'OPEN_MODAL', payload: { msg: 'Start torrent' } });
  };

  const getTVFolder = () => {
    // const self = state;
    post('/guess-tv-show', { torrentName: state.selectedTorrent.name }).then(
      response => {
        const { show, season, error } = response;
        const msg = `Move to ${show} - ${season} folder?`;

        console.log(msg);
        if (error) {
          // handle error ?
        }

        dispatch('openModal', {
          msg,
          show,
          season,
          handleConfirm: () => {
            moveTVShow(state.selectedTorrent, show, season);
          }
        });
      }
    );
  };

  const moveMovie = () => {
    state.isLoading = true;
    post('/move-movie', state.selectedTorrent).then(response => {
      console.log(response);

      if (response.success) {
        removeFromList(state.selectedTorrent);
      }
    });
  };

  const moveTVShow = (
    torrent: TorrentType,
    show: string,
    season: string | number
  ) => {
    state.isLoading = true;
    console.log('Controls will move TV Show');
    console.log(torrent, show, season);
    post('/move-tv-show', { torrent, show, season }).then(response => {
      if (response.success) {
        removeFromList(state.selectedTorrent);
      }
    });
  };

  const removeFromList = (torrent: TxTorrent) => {
    state.isLoading = true;
    _delete('/torrents', { id: torrent.id }).then(response => {
      console.log('removing torrents from list.');
      console.log(response);

      dispatch('torrentListShouldChange');
      state.isLoading = false;
    });
  };

  const handleStartStop = () => {
    post('/pause', {
      id: state.selectedTorrent.id,
      action: playPauseText.toLowerCase()
    }).then(response => {
      console.log(`start/stop response`, response);
      dispatch('torrentListShouldChange');
    });
  };

  return (
    <div
      className="controls"
      onClick={e => {
        console.log('ctrls click');
        e.stopPropagation();
        dispatch({ type: 'DESELECT_TORRENT' });
      }}
    >
      <div className="status-bar">
        <div className="vpnStatus indicator">
          VPN
          <div
            className={classNames('statusLight', {
              active: state.vpnStatus === 'ACTIVE'
            })}
          ></div>
        </div>
        {state.isLoading ? (
          <div className="loading-indicator indicator">
            <img src={spinnerImage} width="25" alt="loading" />
          </div>
        ) : null}
      </div>
      <button onClick={toggleVPN}>Toggle VPN</button>
      <button
        onClick={() => {
          getTVFolder();
        }}
        disabled={disabled}
      >
        Move to TV Shows
        <img src={plexIcon} width="25" alt="plex icon" />
      </button>
      <button
        onClick={() => {
          moveMovie();
        }}
        disabled={disabled}
      >
        Move to Movies
        <img src={plexIcon} width="25" alt="plex icon" />
      </button>

      {disabled ? null : (
        <button
          disabled={disabled}
          onClick={() => {
            handleStartStop();
          }}
        >
          {playPauseText}
        </button>
      )}

      {disabled ? null : (
        <button
          onClick={() => {
            removeFromList(state.selectedTorrent);
          }}
          className="danger"
        >
          Remove
        </button>
      )}
    </div>
  );
}
