// react-front-end/src/components/Transmission.tsx
import React, { useEffect } from 'react';
import './styles/transmission.scss';
import Torrent from './Torrent';
import { useGlobalState } from '../State';
import { get } from '../functions';

export default function Transmission() {
  const [state, dispatch] = useGlobalState();
  const { torrents } = state;

  useEffect(() => {
    get('/torrents').then(response => {
      dispatch({ type: 'GOT_TORRENTS', payload: response.torrents });
    });
  }, []);

  let mappedTorrents = '';

  if (torrents && !!torrents.length) {
    mappedTorrents = torrents.map((t: any) => <Torrent data={t} key={t.id} />);
  }

  return (
    <div
      className="transmission"
      onClick={e => {
        console.log('tx click');
        e.stopPropagation();
        dispatch({ type: 'DESELECT_TORRENT' });
      }}
    >
      {mappedTorrents}
    </div>
  );
}

// front-end/src/components/Transmission.vue
<template>
  <div class="transmission">
    <torrent v-for="torrent in torrents" :key="torrent.id" :torrent="torrent" />
  </div>
</template>

<script>
import Torrent from "./Torrent";
import { get } from "../functions";
export default {
  components: {
    Torrent
  },
  data() {
    return {
      torrents: []
    };
  },

  mounted() {
    get("/torrents").then(data => {
      this.torrents = data.torrents;
    });
    // console.log(this.torrents);
  }
};
</script>

<style lang="scss">
.transmission {
  width: 100%;
  height: 100vh;
  padding: 1em;
  overflow-y: auto;
  background-color: #3b3b48;
  color: white;
}
</style>
